services:

  lostfound:
    image: lumijiez/lostfound-service:latest
    container_name: lostfound-service
    depends_on:
      - lfs_postgres
    ports:
      - "${LFS_SERVICE_PORT}:80"
    environment:
      POSTGRES_HOST: lfs_postgres
      POSTGRES_PORT: ${LFS_POSTGRES_PORT}
      POSTGRES_DB: ${LFS_POSTGRES_DB}
      POSTGRES_USER: ${LFS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LFS_POSTGRES_PASSWORD}
      ConnectionStrings__DefaultConnection: "Host=lfs_postgres;Port=5432;Database=${LFS_POSTGRES_DB};Username=${LFS_POSTGRES_USER};Password=${LFS_POSTGRES_PASSWORD}"
    restart: always
    command: >
      /bin/sh -c "
      echo 'Waiting for Postgres to be ready...' &&
      until pg_isready -h lfs_postgres -p ${LFS_POSTGRES_PORT} -U ${LFS_POSTGRES_USER}; do
        sleep 2
      done &&
      echo 'Postgres ready, starting Lost & Found service...' &&
      dotnet LostFound.dll
      "

  budgeting:
    image: lumijiez/budgeting-service:latest
    container_name: budgeting-service
    depends_on:
      - bs_postgres
    ports:
      - "${BS_SERVICE_PORT}:80"
    environment:
      POSTGRES_HOST: bs_postgres
      POSTGRES_PORT: ${BS_POSTGRES_PORT}
      POSTGRES_DB: ${BS_POSTGRES_DB}
      POSTGRES_USER: ${BS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BS_POSTGRES_PASSWORD}
      ConnectionStrings__DefaultConnection: "Host=bs_postgres;Port=5432;Database=${BS_POSTGRES_DB};Username=${BS_POSTGRES_USER};Password=${BS_POSTGRES_PASSWORD}"
    restart: always
    command: >
      /bin/sh -c "
      echo 'Waiting for Postgres to be ready...' &&
      until pg_isready -h bs_postgres -p ${BS_POSTGRES_PORT} -U ${BS_POSTGRES_USER}; do
        sleep 2
      done &&
      echo 'Postgres ready, starting Lost & Found service...' &&
      dotnet Budgeting.dll
      "

  lfs_postgres:
    image: postgres:15
    container_name: lostfound-service-db
    restart: always
    environment:
      POSTGRES_DB: ${LFS_POSTGRES_DB}
      POSTGRES_USER: ${LFS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LFS_POSTGRES_PASSWORD}
    ports:
      - "${LFS_POSTGRES_PORT}:5432"
    volumes:
      - lfs_postgres_data:/var/lib/postgresql/data

  bs_postgres:
    image: postgres:15
    container_name: budgeting-service-db
    restart: always
    environment:
      POSTGRES_DB: ${BS_POSTGRES_DB}
      POSTGRES_USER: ${BS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BS_POSTGRES_PASSWORD}
    ports:
      - "${BS_POSTGRES_PORT}:5432"
    volumes:
      - bs_postgres_data:/var/lib/postgresql/data

volumes:
  lfs_postgres_data:
  bs_postgres_data:
