version: "3.9"

services:

  lostfound:
    image: lumijiez/lostfound-service:latest
    container_name: lostfound-service
    depends_on:
      - lfs_postgres
    ports:
      - "${LFS_SERVICE_PORT}:80"
    environment:
      POSTGRES_HOST: lfs_postgres
      POSTGRES_PORT: ${LFS_POSTGRES_PORT}
      POSTGRES_DB: ${LFS_POSTGRES_DB}
      POSTGRES_USER: ${LFS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LFS_POSTGRES_PASSWORD}
      ConnectionStrings__DefaultConnection: "Host=lfs_postgres;Port=${LFS_POSTGRES_PORT};Database=${LFS_POSTGRES_DB};Username=${LFS_POSTGRES_USER};Password=${LFS_POSTGRES_PASSWORD}"
    restart: always
    command: >
      /bin/sh -c "
      echo 'Waiting for Postgres to be ready...' &&
      until pg_isready -h lfs_postgres -p ${LFS_POSTGRES_PORT} -U ${LFS_POSTGRES_USER}; do
        sleep 2
      done &&
      echo 'Postgres ready, starting Lost & Found service...' &&
      dotnet LostFoundService.dll
      "

  lfs_postgres:
    image: postgres:15
    container_name: lostfound-service-db
    restart: always
    environment:
      POSTGRES_DB: ${LFS_POSTGRES_DB}
      POSTGRES_USER: ${LFS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LFS_POSTGRES_PASSWORD}
    ports:
      - "${LFS_POSTGRES_PORT}:5432"
    volumes:
      - lfs_postgres_data:/var/lib/postgresql/data
      - ./seed/lostfound-service/seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  lfs_postgres_data:
