name: Branch Name Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          echo "Checking branch name: $BRANCH_NAME"
          
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|chore|docs)/[a-z0-9-]+/[a-z0-9-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow convention: type/scope/short-description"
            exit 1
          fi
          
          echo "Branch name is valid"
