name: Auto Rebase main -> dev

on:
  push:
    branches:
      - main

jobs:
  rebase-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT for checkout too
          
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Rebase dev onto main and push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch origin
          git checkout -B dev origin/dev
          git rebase origin/main
          git push origin dev --force-with-lease
