name: Auto Rebase main -> dev

on:
  push:
    branches:
      - main

jobs:
  rebase-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Configure git to use PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://${PAT_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Rebase dev onto main and push
        run: |
          git fetch origin
          git checkout dev
          git rebase origin/main
          git push origin dev --force
